# Generated by Django 2.2.6 on 2020-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0016_auto_20200801_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(to='p_library.Friend'),
        ),
    ]
